from enum import Enum

DEFAULT_DEPTH = 20
DEFAULT_MSG_LIMIT = 20
DEFAULT_MSG_LIMIT_PERIOD_HOURS = 1
DEFAULT_BAN_PERIOD_HOURS = 4
DEFAULT_MAX_COMPLAINT_COUNT = 3
DEFAULT_MODERATION_CYCLE_SECS = 5


class ChatType(str, Enum):
    COMMON = "common"
    PRIVATE = "private"
