import os
from dotenv import load_dotenv

load_dotenv()

# Server Settings
DEFAULT_HOST = os.getenv("HOST", "127.0.0.1")
DEFAULT_PORT = os.getenv("PORT", 8001)
DEFAULT_SERVER_BUFFER_LIMIT = 2**16
DEFAULT_MSG_COUNT = os.getenv("MSG_COUNT", 20)
DEFAULT_MSG_LIMIT = os.getenv("MSG_LIMIT", 20)
DEFAULT_MSG_LIMIT_PERIOD_HOURS = os.getenv("MSG_LIMIT_PERIOD_HOURS", 1)
DEFAULT_BAN_PERIOD_HOURS = os.getenv("BAN_PERIOD_HOURS", 4)
DEFAULT_MAX_COMPLAINT_COUNT = os.getenv("MAX_COMPLAINT_COUNT", 3)
DEFAULT_MODERATION_CYCLE_SECS = os.getenv("MODERATION_CYCLE_SECS", 5)
DEFAULT_TZ = os.getenv("DEFAULT_TZ", "Europe/Moscow")

# Database Settings
DEFAULT_MAX_CONNECTIONS = os.getenv("MAX_CONNECTIONS", 1)
DEFAULT_DB_CONNECTION_WAIT_SECS = 0.001
